# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170924_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Nội Dung'),
        ),
    ]
