# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tintuc_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='slug',
            field=models.SlugField(),
        ),
    ]
