# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170926_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
