# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170926_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tintuc',
            name='slug',
        ),
    ]
