# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_tintuc_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tintuc',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
