# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170930_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tintuc',
            name='Title',
        ),
    ]
