# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_tintuc_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tintuc',
            name='Title',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
