# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 13:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_tintuc_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='Content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Noi dung'),
        ),
        migrations.AlterField(
            model_name='tintuc',
            name='Decriptions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tintuc',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
