# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20171008_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='Title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
